### ISSUE TITLE
children-not-last

### ISSUE THREAD

**Issue by sulaiman1073** [benface/tailwindcss-children#12]
Often you would want to do something like:

```css
.someClass > *:not(:last-child) {
  margin-bottom: 8px
}
```
So children-not-last would be really handy.
