### ISSUE TITLE
children:hover not applied correctly

### ISSUE THREAD

**Issue by SamGoody** [benface/tailwindcss-children#34]
:hover is not working as documented/expected.  
It is being applied to parent instead of children.

### actual children.css
```css
.children\:hover\:block:hover > * {
  display: block;
}
```

### expected children.css
```css
.children\:hover\:block > :hover {
  display: block;
}
```

### children.html
```html
<!doctype html>
<html>
<head>
	<title>Children Test</title>
	<link href="./children.css" rel="stylesheet">
</head>
<body>
	<div class="children:hover:block">
		<i>Alice</i>
		<i>Bob</i>
	</div>
</body>
</html>
```

### tailwing.config
```javascript
module.exports = {
  content: [
    "./children.html"
  ],
  theme: {
    extend: {},
  },
  variants: {
    display: ['children', 'default', 'children-hover', 'hover'],
  },
  plugins: [
    require('tailwindcss-children'),
  ],
}
```

### command used:
```bash
$ npx tailwindcss -i ./base.css -o ./children.css
```

### package.json:
```json
{
  "devDependencies": {
    "autoprefixer": "^10.4.2",
    "postcss": "^8.4.5",
    "tailwindcss": "^3.0.15",
    "tailwindcss-children": "^2.1.0"
  },
  "dependencies": {
    "@tailwindcss/forms": "^0.4.0"
  }
}
```
